const FLAG_CODES: Record<string, string> = {
  "Alemanha": "de",
  "Argentina": "ar",
  "Argélia": "dz",
  "Arábia Saudita": "sa",
  "Austrália": "au",
  "Brasil": "br",
  "Bélgica": "be",
  "Bósnia e Herzegovina": "ba",
  "Cabo Verde": "cv",
  "Canadá": "ca",
  "Catar": "qa",
  "Colômbia": "co",
  "Coreia do Sul": "kr",
  "Costa do Marfim": "ci",
  "Croácia": "hr",
  "Curaçao": "cw",
  "Egito": "eg",
  "Equador": "ec",
  "Escócia": "gb-sct",
  "Espanha": "es",
  "Estados Unidos": "us",
  "França": "fr",
  "Gana": "gh",
  "Haiti": "ht",
  "Inglaterra": "gb-eng",
  "Iraque": "iq",
  "Irã": "ir",
  "Japão": "jp",
  "Jordânia": "jo",
  "Marrocos": "ma",
  "México": "mx",
  "Noruega": "no",
  "Nova Zelândia": "nz",
  "Panamá": "pa",
  "Paraguai": "py",
  "Países Baixos": "nl",
  "Portugal": "pt",
  "RD Congo": "cd",
  "República Tcheca": "cz",
  "Senegal": "sn",
  "Suécia": "se",
  "Suíça": "ch",
  "Tunísia": "tn",
  "Turquia": "tr",
  "Uruguai": "uy",
  "Uzbequistão": "uz",
  "África do Sul": "za",
  "Áustria": "at",
};

export function getFlagUrl(teamName: string): string | null {
  const code = FLAG_CODES[teamName];
  return code ? `https://flagcdn.com/w40/${code}.png` : null;
}
